language: node_js
node_js:
  - node
  - 10
script:
  - npm run lint
  - npm run test
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 60
after_success:
  - NODE_ENV=production npm run build
  - semantic-release
notifications:
  email: false
sudo: false
